image: ubuntu:bionic

stages:
  - snapcraft
  - build

before_script:
  - export LC_ALL=C.UTF-8
  - export LANG=C.UTF-8
  - export SNAP_ARCH=amd64
  - export PATH=/snap/bin:$PATH

prepare-snapcraft:
  stage: snapcraft
  script: |
      apt-get update && \
      apt-get install --yes curl sudo jq squashfs-tools && \
      curl -L $(curl -H 'X-Ubuntu-Series: 16' 'https://api.snapcraft.io/api/v1/snaps/details/core' | jq '.download_url' -r) --output core.snap && \
      mkdir -p /snap/core && \
      unsquashfs -d /snap/core/current core.snap && \
      rm core.snap && \
      curl -L $(curl -H 'X-Ubuntu-Series: 16' 'https://api.snapcraft.io/api/v1/snaps/details/snapcraft?channel=candidate' | jq '.download_url' -r) --output snapcraft.snap && \
      mkdir -p /snap/snapcraft && \
      unsquashfs -d /snap/snapcraft/current snapcraft.snap && \
      rm snapcraft.snap && \
      curl -L https://raw.githubusercontent.com/snapcore/snapcraft/master/docker/bin/snapcraft-wrapper --output snapcraft-wrapper && \
      mv snapcraft-wrapper /snap/bin/snapcraft && \
      chmod a+x /snap/bin/snapcraft

build-gnome-3-28-1804-sdk-snap:
  stage: build
  script:
    - echo $LOGIN | snapcraft login --with -
    - SNAPCRAFT_SETUP_CORE=1 snapcraft
    - snapcraft push *.snap --release edge
    - snapcraft logout
