image: ubuntudesktop/gnome-3-28-1804

stages:
  - build

before_script:
  - export LC_ALL=C.UTF-8
  - export LANG=C.UTF-8
  - export SNAP_ARCH=amd64
  - export PATH=/snap/bin:$PATH
  - apt-get update

build-gnome-3-28-1804-sdk-snap:
  stage: build
  script:
    - echo $LOGIN | snapcraft login --with -

    - ln -s sdk-snapcraft.yaml snapcraft.yaml
    - SNAPCRAFT_SETUP_CORE=1 snapcraft --destructive-mode
    - snapcraft push gnome-3-28-1804-sdk_*.snap --release edge

    - rm snapcraft.yaml

    - ln -s platform-snapcraft.yaml snapcraft.yaml
    - SNAPCRAFT_SETUP_CORE=1 snapcraft --destructive-mode
    - snapcraft push gnome-3-28-1804_*.snap --release edge

    - snapcraft logout
  allow_failure: false
  artifacts:
    paths: ['./*.snap']
    expire_in: 3 days
