image: ubuntudesktop/gnome-3-28-1804

stages:
  - build

before_script:
  - export LC_ALL=C.UTF-8
  - export LANG=C.UTF-8
  - export SNAP_ARCH=amd64
  - export PATH=/snap/bin:$PATH

build-gnome-3-28-1804-sdk-snap:
  stage: build
  script:
    - echo $LOGIN | snapcraft login --with -
    - SNAPCRAFT_SETUP_CORE=1 snapcraft --destructive-mode
    - snapcraft logout
    - |
       if [ "$CI_COMMIT_REF_NAME" = "master" ]; then
         echo $LOGIN | snapcraft login --with -
         snapcraft push *.snap --release edge
         snapcraft logout
       fi
  allow_failure: false
  artifacts:
    paths: ['./*.snap']
    expire_in: 3 days
