image: snapcore/snapcraft:candidate

stages:
  - build

before_script:
  - export LC_ALL=C.UTF-8
  - export LANG=C.UTF-8
  - export SNAP_ARCH=amd64
  - apt-get -y update
  - apt-get -y dist-upgrade

build-gnome-3-28-1804-sdk-snap:
  stage: build
  script:
    - echo $LOGIN | snapcraft login --with -
    - SNAPCRAFT_SETUP_CORE=1 snapcraft
    - snapcraft push *.snap --release edge
    - snapcraft logout
