name: test-dependencies
on:
  pull_request:
  push:
    branches:
      - gnome-42-2204-sdk

jobs:
  check-deps:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:rolling
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies (Ubuntu)
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends python3 python3-yaml
      - name: Verify dependencies
        run: |
          tools/check_dependencies.py
